// HOME PAGE
export const GET_OVERVIEW = 'GET_OVERVIEW';
// SEARCH & STOCK LIST
export const GET_STOCKS = 'GET_STOCKS';
export const SEARCH_STOCKS = 'SEARCH_STOCKS';
// STOCK INFORMATION
export const GET_STOCK_INFO = 'GET_STOCK_INFO';
// PAGINATION
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
